sonar.projectKey=gr-frontend
sonar.projectName=GameReview Frontend
sonar.host.url=http://localhost:9000
sonar.token=squ_209eeb5307354b361d039cb67ea69fdb492cf328

sonar.sources=src/app
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test.ts,**/polyfills.ts,**/main.ts
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
